### PR TITLE
Also retry on status code 500 (unexpected condition)

### PR DESCRIPTION
**Pull request by SamVanBelle**

### CODE REVIEW

**Comment by SamVanBelle** [comment]
@ININDevEvangelists Can you please merge this PR? One of our customers encountered status code 500. Thanks.
Best regards,
Sam Van Belle
XQTING

**Comment by dginty4** [comment]
@SamVanBelle I am going to close this PR. The dotnet sdk, like all of our sdks, are generated from our swagger docs and posted to this repo so any changes made to this repo will be overwritten when the next sdk version is released. If you wish to open a PR to change the dotnet sdk you can do so on [this repo](https://github.com/purecloudlabs/platform-client-sdk-common) or alternatively you can post on our discussion forum about the problem and someone should be able to help you

**Comment by timsmithgenesys** [comment]
@SamVanBelle a 500 response code is not considered retryable. Only 429, 502, 503, and 504 are considered retryable. Source: https://developer.genesys.cloud/platform/api/rate-limits#retrying-other-responses

If you are encountering 500 errors, please open a case with Genesys Cloud Care; 500 responses cannot be investigated via the forum.

**Comment by SamVanBelle** [comment]
Thanks @timsmithgenesys for your reply.
The problem is the 500 error occurred while subscribing to queue notifications. Missing these notifications leads to a non-functional system.
What about a retry 5 minutes later (based on our log Genesys Cloud looks stable again 5 mins later)?

I'll also open a case at Genesys Cloud Care.

**Comment by timsmithgenesys** [comment]
The difference between a 500 and one of the 5xx codes listed as retryable is that 502, 503, and 504 errors are known to be temporal conditions that should resolve very quickly. One very common case is that if your request happens to land just right during a scale-up event, it may be routed to an instance that wasn't quite ready to handle the request. In a few seconds time, the condition should be resolved. 

A 500 error, on the other hand, is an actual error condition within the Genesys Cloud services. This means that some backend service encountered an internal error while processing the request. Because 500 errors are never expected and directly indicates a failure within the services, it must always be investigated by Care as a bug report. 

Your application will handle these responses differently. It should have logic to wait a brief period and retry the request for the retryable codes. Encountering these codes is a temporal condition and an application can be expected to self-heal in a brief period of time.  When a 500 is encountered, this represents an unexpected failure and the application will need to take different steps to recover and notify the end user and administrators of the failure. Automatically retrying 500 errors can easily lead to abusive patterns with the platform that could cause your application to be disabled entirely. That's not to say a single retry is problematic, but unleashing a barrage of repeated requests that cause 500 error is an abusive pattern. A better approach would be to use your on-call paging system to page someone to investigate and retry the process manually if it's believed that is an appropriate course of action based on the details of the issue from your application's logging.

Optimally, 500 responses should be very few and far between and shouldn't require building automation to work around them (but the retryable ones should). If this is a persistent problem, please be sure to make Care aware that it's not a one time thing and is causing operational stability issues for you.

**Comment by timsmithgenesys** [comment]
> Missing these notifications leads to a non-functional system.

I'll also add that using WebSocket notifications doesn't come with any guarantee of delivery or retrying missed notifications; it's fire and forget and is intended for front-end apps where that isn't an issue because they can just refresh if they get out of sync. If you need guaranteed delivery for data integrity purposes, you need to use the EventBridge integration which does offer guaranteed delivery and retry on failure.

**Pull request closed without merging**
